!==============================================================================
! PROGRAM: main
!
! Authors
! -------
! Dr. Randal J. Barnes
! Department of Civil, Environmental, and Geo- Engineering
! University of Minnesota
! Minneapolis, MN, 55455
!
! Dr. Elizabeth Barnes
! Department of Atmospheric Science
! Colorado State University
! Fort Collins, CO, 80525
!
! Dr. Mark DeMaria
! Cooperative Institute for Research in the Atmosphere
! Colorado State University
! Fort Collins, CO, 80523
!
! Version
! -------
! * 31 January 2023
!
!==============================================================================
program main
   use test_activation_module
   use test_bivariate_normal_module
   use test_model_module
   use test_shash_module

   call test_activation()
   call test_bivariate_normal()
   call test_model()
   call test_shash()

   ! Run the example execution template.
   call execution_template()
end program main


!==============================================================================
! SUBROUTINE: execution_template
!
! Present a basic template for using the shash_jht code.
!==============================================================================
subroutine execution_template
   use blueprint_module
   use model_module

   implicit none

   type(Model) :: example_model
   type(Blueprint) :: details

   real(8), dimension(:), allocatable :: x_sample, y_result

   !-----------------------------------
   ! Example: shash3
   !-----------------------------------

   ! Read in the weights, biases, etc from the blueprint file, which was
   ! generated by the trained neural network.
   !details = read_blueprint(".\data\intensity_shash3_test_blueprint.json")
   details = read_blueprint("./data/intensity_shash3_test_blueprint.json")

   ! Initialize the weights, biases, etc in the model.
   call initialize(example_model, details)

   ! Enter a vector of predictors: x_sample.  The predictors for the model
   ! are itemized near the top of the blueprint file as "input_names".
   !
   ! In this example case, we specify a set of values. During implementation
   ! these will be entered by a user or read from a file.
   !
   ! At the time that we created this example, there were 16 components in the
   ! x vector (this might change in the future).  These components are:
   ! "VMAX0", "VMXC", "NCI", "OFDV", "DSDV", "LGDV", "HWDV", "AVDV", "DV12",
   ! "SLAT", "SSTN", "SHDC", "DTL", "T200", "D200", "RHMD".
   x_sample = [30.0, 43.5, 4.0, 1.5, 4.5, -5.5, 1.5, -0.5, 0.0, &
      11.1, 28.6, 7.1, 812.4, -53.5, 97.0, 75.0]

   ! Compute the vector of model predictions.  The predictions for the model
   ! are itemized near the top of the blueprint file as "output_names".
   !
   ! For the SHASH model there are 4 components to an output vector.  These
   ! components are: "mu", "sigma", "gamma", "tau".
   y_result = employ(example_model, x_sample)

   ! Do with the predictions what you will.
   write(*,*) "SHASH3 example results"
   write(*,*) y_result

   !-----------------------------------
   ! Example: bivariate normal
   !-----------------------------------

   ! Read in the weights, biases, etc from the blueprint file, which was
   ! generated by the trained neural network.
   details = read_blueprint("./data/track_bivariate_normal_test_blueprint.json")

   ! Initialize the weights, biases, etc in the model.
   call initialize(example_model, details)

   ! Enter a vector of predictors: x_sample.  The predictors for the model
   ! are itemized near the top of the blueprint file as "input_names".
   !
   ! In this example case, we specify a set of values. During implementation
   ! these will be entered by a user or read from a file.
   !
   ! At the time that we created this example, there were 22 components in the
   ! x vector (this might change in the future).  These components are:
   ! "NCT", "VMAX0", "AVDX", "EMDX", "EGDX", "HWDX", "AVDY", "EMDY", "EGDY",
   ! "HWDY", "LONC", "LATC", "VMXC", "DV12", "SLAT", "SHDC", "SSTN", "DTL",
   ! "DSDV", "LGDV", "HWDV", "AVDV".
   x_sample = [4.0, 55.0, 28.7, -13.0, 28.5, -44.2, -52.8, -75.0, 125.0, &
      2.8, 111.1, 20.5, 37.0, 5.0, 25.0, 9.4, 30.3, 11.6, &
      3.0, 7.0, -5.0, -5.0]

   ! Compute the vector of model predictions.  The predictions for the model
   ! are itemized near the top of the blueprint file as "output_names".
   !
   ! For the SHASH model there are 4 components to an output vector.  These
   ! components are: "mu_u", "mu_v", "sigma_u", "sigma_v",  "rho".
   y_result = employ(example_model, x_sample)

   ! Do with the predictions what you will.
   write(*,*) "Bivariate normal example results"
   write(*,*) y_result

end subroutine execution_template
